version: '3.9'

services:
  server:
    build: ./Server
    container_name: myapp-server
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./Server/.env
    depends_on:
      - mongo

  client:
    build: ./Client
    container_name: myapp-client
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - server

  mongo:
    image: mongo:6
    container_name: myapp-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
