runtime: nodejs20
env: standard
instance_class: F1

env_variables:
  NODE_ENV: production
  PORT: 8080
  VITE_AUTH0_DOMAIN: 'dev-7qqo80kikrtj62it.us.auth0.com'
  VITE_AUTH0_CLIENT_ID: 'BGmxAUNxdB4YAu9US8vNlWn7hNZjHP0c'
  VITE_AUTH0_AUDIENCE: 'https://weather-api'

automatic_scaling:
  max_instances: 20

